[INF-986] Lease renew error callback
matic-insurance/settings_reader-vault_resolver pull request #16
Opened 2022-09-26 12:56 UTC by danpolyuha

2022-09-26 14:27 UTC, volodymyr-mykhailyk requested changes
Thanks for the extension of functionality. However there are couple problems still exist:
- renewal problem will be reported only on the second renewal attempt after a connection was re-established. 
- we do not remove corrupted entry from cache - so new credentials will be retrieved only when existing expires completely
- old issue with entries renewal is still exist. Refresher class tries to renew lease on expired entries

2022-09-26 14:27 UTC, volodymyr-mykhailyk commented on lib/settings_reader/vault_resolver/engines/abstract.rb
> +          return process_renew_auth_error(entry) if auth_error?(e)
If I'm reading this code right way this is what going to happen:

1. Vault failover happens
2. Lease renew triggered
3. Auth error happens
4. Auth initiated
5. We retry renew
6. Lease not found, but an exception will not be caught as it happened outside of the rescue block

2022-09-26 14:27 UTC, volodymyr-mykhailyk commented on lib/settings_reader/vault_resolver/engines/abstract.rb
> +          config.lease_not_found_handler.call(entry)
Should we remove an entry from the cache as well here?

2022-09-28 15:28 UTC, danpolyuha commented
@volodymyr-mykhailyk All comments resolved, please take a look.

2022-09-29 12:51 UTC, volodymyr-mykhailyk approved these changes
🔥

2022-09-29 14:24 UTC, merged